# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack template project 
      run: dotnet pack ./Source/FunctionalProcessing --configuration=Release --output=./Artefacts
    - name: "Publish Artefacts"
      uses: actions/upload-artifact@v2.2.4 
      with:
        name: "drop"
        path: "./Artefacts"
        
  push_nuget:    
    name: "Push to nuget.org" 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Download Artefact"
        uses: actions/download-artifact@v2
        with: 
          name: "drop"
      - name: "Dotnet NuGet Push"
        run: | 
          Get-ChildItem ./ -Filter *.nupkg | 
          Where-Object { !$_.Name.Contains('preview') } | 
          ForEach-Object { dotnet nuget push $_ --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key ${{secrets.NUGET_PUSH_KEY}} } 
        shell: pwsh
